version: '2'

services:

  database:
    image: mysql
    env_file:
      - env/database.env

  pdns:
    build: pdns
    links:
      - database
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "127.0.0.1:8001:80"
    env_file:
      - env/database.env
