version: '2'

services:
  database:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - database.env

  pdns:
    build: .
    links:
      - database
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
    env_file:
      - database.env
